django_project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from mainsite import views

urlpatterns = [
               url(r'^', include('mainsite.urls')),
               #url(r'^mainsite/', include('mainsite.urls')),
               url(r'^admin/', admin.site.urls),
               ]
handler404 = 'views.error404'               
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainsite/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'about/$', views.about, name='about'),
    url(r'services/$', views.services, name='services'),
    url(r'contact/$', views.contact, name='contact'),
    url(r'blog/$', views.blog, name='blog'),
    url(r'portfolio/$', views.projects, name='blog'),
    url(r'gallery/$', views.gallery, name='gallery'),
    url(r'^blog/(?P<BlogPost_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^portfolio/(?P<Post_id>[0-9]+)/$', views.projectdetail, name='projectdetail'),
    url(r'^gallery/(?P<Album_id>[0-9]+)/$', views.photos, name='photos'),
]

mainsite/models.py
from django.db import models

# Create your models here.


class Notification(models.Model):
    notification_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.notification_text

class Post(models.Model):
    title = models.CharField(max_length = 200)
    image = models.FileField()
    image1 = models.FileField()
    image2 = models.FileField()
    image3 = models.FileField()
    image4 = models.FileField()
    content = models.TextField()
    area = models.CharField(max_length = 200)
    time = models.CharField(max_length = 200)
    cost = models.CharField(max_length = 200)
    projectType = models.CharField(max_length = 200)
    projectCategory = models.CharField(max_length = 200)
    projectLocation = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('date published')


    def __str__(self):
        return self.title
class Album(models.Model):
    title = models.CharField(max_length = 200)
    image = models.FileField(null = False, blank = True)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.title
                       
class Photo(models.Model):
    title = 'photo'
    image = models.FileField(null = False, blank = True)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
class BlogPost(models.Model):
    title = models.CharField(max_length = 200)
    author = models.CharField(max_length = 200)
    image = models.FileField(null = True,blank =True) 
    content = models.TextField()
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.title       

mainsite/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Notification,Post,Photo,BlogPost,Album
from django.http import Http404


def index(request):
    latest_notifications = Notification.objects.order_by('-pub_date')[:5]
    context = {'latest_notifications':latest_notifications}

    return render(request, 'mainsite/index.html', context)

def about(request):
    return render(request, 'mainsite/about.html')

def services(request):
    return render(request, 'mainsite/services.html')

def contact(request):
    return render(request, 'mainsite/contact.html')

def projects(request):
    posts = Post.objects.order_by('-pub_date')
    context = {'posts': posts}
    return render(request, 'mainsite/portfolio.html',context)
def gallery(request):
    album = Album.objects.order_by('-pub_date')
    context = {'photos': album}
    return render(request, 'mainsite/gallery.html',context) 
def blog(request):
    posts = BlogPost.objects.order_by('-pub_date')
    paginator = Paginator(posts, 10) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        post = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        post = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        post = paginator.page(paginator.num_pages)
    latest_posts = BlogPost.objects.order_by('-pub_date')[:5]
    return render(request, 'mainsite/blog.html',{'blog': post,'latest_posts':latest_posts,})    
def detail(request, BlogPost_id):
    post = BlogPost.objects.get(pk=BlogPost_id)
    latest_posts = BlogPost.objects.order_by('-pub_date')[:5]
    return render(request, 'mainsite/details.html',{'post': post,'latest_posts':latest_posts,})    

def projectdetail(request, Post_id):   
    post = Post.objects.get(pk=Post_id)
    return render(request, 'mainsite/project.html',{'post': post,}) 

def photos(request,Album_id):
    album = Album.objects.get(pk=Album_id)
    return render(request, 'mainsite/imagegallery.html',{'album': album,})  
def error404(request):
    return HttpResponse("404 PAGE NOT FOUND")       

mainsite/templates/mainsite/about.html
{% extends 'mainsite/base.html' %}
{% load staticfiles %}
{% block main_content %}


    	<section id="about-head">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<h4 class="main-heading">SOMETHING ABOUT US</h4>
					<ol class="breadcrumb">
						 <li><a href="index.html">Home</a></li>
						 <li class="active">About</li>
					</ol>
				</div>
			</div>
		</div>
	</section>
		<section id="dividers-2">
		<div class="row">
			<div class="col-md-6">
				<img class="img-responsive" src="{% static 'img/cv.jpg' %}">
			</div>
			<div class="col-md-6">
				<h4 class="sub-heading-1">Crosslite Infra</h4>
				<p class="sub-content-1" style="text-align: justify;">Crosslite Infra Pvt. Ltd is an engineering, construction company. A strong customer focused approach and the continuous quest for world class quality have enabled it to attain and sustain leadership in all this major lines of business. 
				Crosslite Infra believes that progress must be achieved in harmony with the environment. From our inception, we have taken an aggressive, positive approach to sustainability. We believe that we have responsibility towards our clients and employees; to embed sustainability at every level of our organization. A commitment to community welfare and environmental protection are internal party of the sustainability policy.
				Crosslite Infra is equipped with the requisite expertise and wide range experience to undertake engineering procurement and construction (EPC) projects with single source responsibility. Contracts are executed using state of art design tools and project management techniques from concept to commissioning.</p>
			</div>
		</div>
	</section>
	<section id="dividers-4">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<h4 class="main-heading">MORE ABOUT US</h4>
					<p class="main-content">Professional construction services</p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-3 item text-center">
					<img class="img-responsive" src="{% static 'img/team.jpg' %}">
					<h4 class="sub-heading-1">WE HAVE A STRONG TEAM</h4>
					<p class="sub-content-1">Teamwork is the ability to work together toward a common vision. The ability to direct individual accomplishments toward organizational objectives. It is the fuel that allows common people to attain uncommon results.</p>
				</div>
				<div class="col-md-3 item text-center">
					<img class="img-responsive" src="{% static 'img/custom.jpg' %}">
					<h4 class="sub-heading-1">WE VALUE OUR CLIENTS</h4>
					<p class="sub-content-1">We strive to obtain economic success and achieve complete satisfaction of our customers through our unique combination of comprehensive know-how, local knowledge and extensive international experience.</p>
				</div>
				<div class="col-md-3 item text-center">
					<img class="img-responsive" src="{% static 'img/vision.jpg' %}">
					<h4 class="sub-heading-1">OUR VISION</h4>
					<p class="sub-content-1">To set industrial standard by ensuring effectiveness to our customers, and consistently improve the quality of services in all accepts of construction by holding our core values and commitments to the nature.</p>
				</div>
				<div class="col-md-3 item text-center">
					<img class="img-responsive" src="{% static 'img/mission.jpg' %}">
					<h4 class="sub-heading-1">OUR MISSION</h4>
					<p class="sub-content-1">Our mission is to develop innovative and practical solutions for our customers, whether they are detailed individual services or a complete solution from a single contractor.
					We strive to achieve complete satisfaction of our customers.</p>
				</div>
			</div>
		</div>
	</section>
		<section id="mission">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<h4 class="main-heading">OUR MISSION</h4>
					<p><span class="glyphicon glyphicon-knight" aria-hidden="true"></span></p>
					<p class="main-content">Our mission is to develop innovative and practical solutions for our customers, whether they are detailed individual services or a complete solution from a single contractor.</p>
				</div>
			</div>
		</div>
	</section>


	
{% endblock %}

mainsite/templates/mainsite/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Welcome To Crosslite Infra</title>
	<link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/lightbox.css' %}">
</head>
<body>
	<header>
        <nav class="navbar navbar-default navbar-fixed-top changes">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#home"><img class="logo img-responsive" src="{% static 'img/logo.png' %}"></a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-collapse">
                    <ul id="menu" class="nav navbar-nav navbar-left">
                        <li data-menuanchor="home"><a href="/">Home</a></li>
                        <li data-menuanchor="services"><a href="/services/">Services</a></li>
                        <li data-menuanchor="portfolio"><a href="/portfolio/">Portfolio</a></li>
						<li data-menuanchor="gallery"><a href="/gallery/">Gallery</a></li>
                        <li data-menuanchor="about"><a href="/about/">About Us</a></li>
                        <li data-menuanchor="blog"><a href="/blog/">Blog</a></li>
                        <li data-menuanchor="contact"><a href="/contact/">Contact Us</a></li>
                    </ul>
                    <ul id="menu" class="nav navbar-nav navbar-right">
                        <li><a href="#"><i class="fa fa-instagram fa-lg"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter fa-lg"></i></a></li>
                        <li><a href="#"><i class="fa fa-facebook fa-lg"></i></a></li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>

	{% block main_content %}
    {% endblock %}

    	<section id="get-touch">
		<div class="container ">
			<div class="row">
				<div class="col-md-12 text-center">
					<h4 class="main-heading">GET IN TOUCH</h4>
					<p class="main-content">If you'd like to discuss a project with one of our team, drop us a line on
							+919544720000 or email info@crossliteinfra.com</p>
				</div>
			</div>
			<div class="row get_touch">
				<div class="col-md-4 text-center">
					<p class="sub-heading-2"><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> Telephone</p>
					<p class="sub-content-2">+919544720000</p>
				</div>
				<div class="col-md-4 text-center item-center">
					<p class="sub-heading-2"><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> Address</p>
					<p class="sub-content-2">HOUSE NO 116, ST MARTIN ROAD<br>PALARIVATTAM<br>ERNAKULAM</p>
				</div>
				<div class="col-md-4 text-center">
					<p class="sub-heading-2"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Email</p>
					<p class="sub-content-2">INFO@CROSSLITEINFRA.COM</p>
				</div>
			</div>
		</div>
	</section>

	<footer>
		<div class="row">
			<div class="col-md-12 text-center footer-text">
				<h1>Made with <span class="glyphicon glyphicon-heart"></span>  by <strong><a href="http://www.crypstaltechnolgies.com">Crypstal</a></strong> Designs</h1>
			</div>
	</footer>

	<script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/lightbox.js' %}"></script>
	<script type="text/javascript">
		var i = 1;
		function scroll () {
		   setTimeout(function () {
          	$("#scroll").css("margin-top",i+"px");
		      i--;
		      if (i > -540) {
		         scroll();
		      }
		      else{
		      	i=300;
		      	scroll();
		      }
		   }, 50)
		}
		scroll();

		(function( $ ) {
		    function doAnimations( elems ) {
		        var animEndEv = 'webkitAnimationEnd animationend';

		        elems.each(function () {
		            var $this = $(this),
		                $animationType = $this.data('animation');
		            $this.addClass($animationType).one(animEndEv, function () {
		                $this.removeClass($animationType);
		            });
		        });
		    }
		    var $myCarousel = $('#mycarousel'),
		        $firstAnimatingElems = $myCarousel.find('.item:first').find("[data-animation ^= 'animated']");
		    $myCarousel.carousel();
		    doAnimations($firstAnimatingElems);
		    $myCarousel.carousel('pause');
		    $myCarousel.on('slide.bs.carousel', function (e) {
		        var $animatingElems = $(e.relatedTarget).find("[data-animation ^= 'animated']");
		        doAnimations($animatingElems);
		    });
		})(jQuery);

		  $(window).scroll(function () {
                if ($(document).scrollTop() > 50) {
                    $('nav').addClass('shrink');
                } else {
                    $('nav').removeClass('shrink');
                }
            });
	</script>

</body>
</html>

mainsite/templates/mainsite/blog.html
{% extends 'mainsite/base.html' %}
{% load staticfiles %}
{% block main_content %}

    	<section id="about-head">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<h4 class="main-heading">BLOG</h4>
					<p class="main-content">Our Latest Updates</p>
					<ol class="breadcrumb">
						<li><a href="index.html">Home</a></li>
						<li class="active">Blog</li>
					</ol>
				</div>
			</div>
		</div>
	</section>



<!--    <div class="pagination">
    <span class="step-links">
        {% if blog.has_previous %}
            <a href="?page={{ blog.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ blog.number }} of {{ blog.paginator.num_pages }}.
        </span>

        {% if blog.has_next %}
            <a href="?page={{ blog.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>-->
	<section id="dividers-3">
		<div class="container">
		<div class="col-md-8">
		{% for post in blog %}
			<div class="row">
				<div class="col-md-4">
					<img style="height: 200px; margin: 10px auto;"  src="{{ post.image.url }}" class="img-responsive">
				</div>
				<div class="col-md-8">
				<h2 style="text-transform: uppercase;">{{ post.title }}</h2>
				<p style="float: right;">{{ post.pub_date }}</p>
				<p>{{ post.author }}</p>
				<p style="text-align: justify;" >
				{{ post.content|truncatewords:33 }}
				</p>
				<a href = "{% url 'detail' post.id %}" class="btn btn-default">Read More</a>
				</div>
				</div>
				
			
		{% endfor %} 
		</div>

			<div class="col-md-4">
			<h3>Latest Posts</h3>
			<div class="posts">
		{% for latest_post in latest_posts %}
			<div class="row">
			<div class="col-md-4">
				<img style="height: 70px; margin: 10px auto;" src="{{ latest_post.image.url }}" class="img-responsive">
			</div>
			<div class="col-md-8">
				<h4 style="margin:0;">{{ latest_post.title }}</h4>
				<p style="text-align: justify; font-size: 12px;" >
				{{ latest_post.content|truncatewords:10 }}
				</p>
			<a href="{% url 'detail' latest_post.id %}">Read More</a>
			</div>
			</div>

		{% endfor %}
		</div> 			
			</div>
		</div>
		<div class="row">
		<div class="col-md-6 text-center">
			<ul class="pagination">
            {% if blog.has_previous %}
                <li><a href="?page=1"><<</a></li>
                <li><a href="?page={{ blog.previous_page_number }}"><</a></li>
            {% endif %}

            {% for i in blog.paginator.page_range %}
                <li {% if blog.number == i %} class="active" {% endif %}><a href="?page={{i}}">{{i}}</a></li>
            {% endfor %}

            {% if blog.has_next %}
                <li><a href="?page={{ blog.next_page_number }}">></a></li>
                <li><a href="?page={{ blog.paginator.num_pages }}">>></a></li>
            {% endif %}
		</ul>
		</div>	
		</div>
	</section>
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.9";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>

{% endblock %}

mainsite/templates/mainsite/contact.html
{% extends 'mainsite/base.html' %}
{% load staticfiles %}
{% block main_content %}

    	<section id="about-head">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<h4 class="main-heading">GET IN TOUCH</h4>
					<p class="main-content">All to contact us</p>
					<ol class="breadcrumb">
						<li><a href="index.html">Home</a></li>
						<li class="active">Contact</li>
					</ol>
				</div>
			</div>
		</div>
	</section>
	<section id ="contact-form">
		<div class="row">
			<div class="col-md-5">
			</div>
			<div class="col-md-7">
				<h4 class="main-heading">CONTACT FORM</h4>
				<form class="row">
					  <div class="col-md-6 input">
					    <label >First Name</label>
					    <input type="text" class="form-control"  placeholder="First Name">
					  </div>
					  <div class="col-md-6 input">
					    <label >Last Name</label>
					    <input type="text" class="form-control" placeholder="Last Name">
					  </div>
					   <div class="col-md-6 input">
					    <label >Email</label>
					    <input type="text" class="form-control"  aria-describedby="emailHelp" placeholder="Email">
					    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
					  </div>
					  	<div class="col-md-6 input">
					    <label >Phone Number</label>
					    <input type="text" class="form-control"  placeholder="Phone Number">
					  </div>
					  <div class="col-md-12 input">
					    <label >Write your message here</label>
					    <textarea class="form-control" rows="6"></textarea>
					  </div>
					  <div class="col-md-12 input">
					  <button type="submit" class="btn btn-primary">SEND MESSAGE</button>
					  </div>
					</form>
			</div>
		</div>	
	</section>
	<section id="contact-map">
		<div class="row">
			<div class="col-md-12 text-center">
				<div class="container">
						 <h4 class="main-heading">VIEW US ON GOOGLE MAP</h4>
						 <p class="main-content">You can find us on google map<br>
												 </p>
				</div>
			</div>	
		</div>
		<div class="row">
			<div class="col-md-12">
				<div id="map"></div>
			</div>
		</div>
	</section>
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAXYfg-eTUhPJV-vJsOG6WPbvwkbzEsSdU"></script>

        <script type="text/javascript">
            // When the window has finished loading create our google map below
            google.maps.event.addDomListener(window, 'load', init);

            function init() {
                // Basic options for a simple Google Map
                // For more options see: https://developers.google.com/maps/documentation/javascript/reference#MapOptions
                var mapOptions = {
                    // How zoomed in you want the map to start at (always required)
                    zoom: 15,
                    scrollwheel: false,

                    // The latitude and longitude to center the map (always required)
                    center: new google.maps.LatLng(9.0513988, 76.5361174), // New York

                    // How you would like to style the map.
                    // This is where you would paste any style found on Snazzy Maps.
                    styles: [{"featureType":"administrative","elementType":"all","stylers":[{"saturation":"-100"}]},{"featureType":"administrative.province","elementType":"all","stylers":[{"visibility":"off"}]},{"featureType":"landscape","elementType":"all","stylers":[{"saturation":-100},{"lightness":65},{"visibility":"on"}]},{"featureType":"poi","elementType":"all","stylers":[{"saturation":-100},{"lightness":"50"},{"visibility":"simplified"}]},{"featureType":"road","elementType":"all","stylers":[{"saturation":"-100"}]},{"featureType":"road.highway","elementType":"all","stylers":[{"visibility":"simplified"}]},{"featureType":"road.arterial","elementType":"all","stylers":[{"lightness":"30"}]},{"featureType":"road.local","elementType":"all","stylers":[{"lightness":"40"}]},{"featureType":"transit","elementType":"all","stylers":[{"saturation":-100},{"visibility":"simplified"}]},{"featureType":"water","elementType":"geometry","stylers":[{"hue":"#ffff00"},{"lightness":-25},{"saturation":-97}]},{"featureType":"water","elementType":"labels","stylers":[{"lightness":-25},{"saturation":-100}]}]
                };

                // Get the HTML DOM element that will contain your map
                // We are using a div with id="map" seen below in the <body>
                var mapElement = document.getElementById('map');

                // Create the Google Map using our element and options defined above
                var map = new google.maps.Map(mapElement, mapOptions);

                // Let's also add a marker while we're at it
                var marker = new google.maps.Marker({
                    position: new google.maps.LatLng(40.6700, -73.9400),
                    map: map,
                    title: 'Snazzy!'
                });
            }
        </script>

{% endblock %}

mainsite/templates/mainsite/details.html
{% extends 'mainsite/base.html' %}
{% load staticfiles %}
{% block main_content %}

    	<section id="about-head">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<h4 class="main-heading">BLOG</h4>
					<p class="main-content">Our Latest Updates</p>
					<ol class="breadcrumb">
						<li><a href="index.html">Home</a></li>
						<li class="active">Blog</li>
					</ol>
				</div>
			</div>
		</div>
	</section>



<!--    <div class="pagination">
    <span class="step-links">
        {% if blog.has_previous %}
            <a href="?page={{ blog.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ blog.number }} of {{ blog.paginator.num_pages }}.
        </span>

        {% if blog.has_next %}
            <a href="?page={{ blog.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>-->
	<section id="dividers-3">
		<div class="container">
			<div class="col-md-8">
				<h1 style="text-transform: uppercase;">{{ post.title }}</h1>
				<p style="float: right;">{{ post.pub_date }}</p>
				<p>{{ post.author }}</p>
				<img style="height:500px;margin: 0 auto;" src="{{ post.image.url }}" class="img-responsive">
				<p style="text-align: justify; margin: : 20px;" >
				{{ post.content }}
				</p>
				<div style="float: right;" class="fb-share-button" 
				    data-href="{% url 'detail' post.id %}"
				    data-size ="large"
				    data-layout="button_count">
				  </div>
			</div>  	
			<div class="col-md-4">
			<h3>Latest Posts</h3>
			<div class="posts">
		{% for latest_post in latest_posts %}
			<div class="row">
			<div class="col-md-4">
				<img src="{{ latest_post.image.url }}" class="img-responsive">
			</div>
			<div class="col-md-8">
				<h4 style="margin:0;">{{ latest_post.title }}</h4>
				<a href="{% url 'detail' latest_post.id %}">Read More</a>
			</div>
			</div>

		{% endfor %}
		</div> 			
			</div>
		</div>
	</section>





	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.9";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>

{% endblock %}

mainsite/templates/mainsite/gallery.html
{% extends 'mainsite/base.html' %}
{% load staticfiles %}
{% block main_content %}

    	<section id="about-head">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<h4 class="main-heading">GALLERY</h4>
					<p class="main-content">Our Gallery</p>
					<ol class="breadcrumb">
						<li><a href="index.html">Home</a></li>
						<li class="active">GALLERY</li>
					</ol>
				</div>
			</div>
		</div>
	</section>

	 <section id="dividers-3">
        <div class="container">
            <div class="row">

                {% for photo in photos %}
                    <div class="col-md-4">
                    <div style="height:200px;" class="image-rotate-scale">
                       <a href="{% url 'photos' photo.id %}"><img class="img-responsive" src="{{ photo.image.url }}"></a>
                    </div>
                    <h4 class="sub-heading-1">{{ photo.title }}</h4>
                    </div>
                {% endfor %}

            </div>
        </div>
    </section>

{% endblock %}

mainsite/templates/mainsite/imagegallery.html
{% extends 'mainsite/base.html' %}
{% load staticfiles %}
{% block main_content %}

    	<section id="about-head">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<h4 class="main-heading">GALLERY</h4>
					<p class="main-content">Our Gallery</p>
					<ol class="breadcrumb">
						<li><a href="index.html">Home</a></li>
						<li class="active">GALLERY</li>
					</ol>
				</div>
			</div>
		</div>
	</section>

	 <section id="dividers-3">
        <div class="container">
            <div class="row">

                {% for photo in album.photo_set.all %}
                    <div class="col-md-4">
                    <div style="height:200px;" class="image-rotate-scale">
                       <a href="{{ photo.image.url }}" data-lightbox="image-1"><img class="img-responsive" data-lightbox="image-1" src="{{ photo.image.url }}"></a>
                    </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </section>

{% endblock %}

mainsite/templates/mainsite/portfolio.html
{% extends 'mainsite/base.html' %}
{% load staticfiles %}
{% block main_content %}

    	<section id="about-head">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<h4 class="main-heading">PORTFOLIO</h4>
					<p class="main-content">Our Works</p>
					<ol class="breadcrumb">
						<li><a href="index.html">Home</a></li>
						<li class="active">Portfolio</li>
					</ol>
				</div>
			</div>
		</div>
	</section>

    <section id="dividers-3">
        <div class="container">
            <div class="row">
            
                {% for post in posts %}
                    <div class="col-md-4">
                    <div class="image-rotate-scale">
                        <img style="height: 300px;" class="img-responsive" src="{{ post.image.url }}">
                    </div>
                    <h4 class="sub-heading-1">{{ post.title }}</h4>
                    <h6>{{ post.pub_date }}</h6>
                    <p class="sub-content-1">{{ post.content|truncatewords:10 }}</p>
                    <a href="{% url 'projectdetail' post.id %}" class="btn btn-default">READ MORE</a>
                    </div>
                {% endfor %}    

            </div>
        </div>
    </section>

{% endblock %}